#!/usr/bin/env python3
"""Convert Instagram cookies from JSON to Netscape format for yt-dlp."""
import json

def json_to_netscape(json_file, output_file):
    """Convert JSON cookies to Netscape format."""
    with open(json_file, 'r') as f:
        cookies = json.load(f)

    with open(output_file, 'w') as f:
        f.write("# Netscape HTTP Cookie File\n")
        f.write("# This file was generated by convert_cookies.py\n")
        f.write("# Edit at your own risk.\n\n")

        for cookie in cookies:
            domain = cookie.get('domain', '')
            host_only = 'FALSE' if cookie.get('hostOnly', False) else 'TRUE'
            path = cookie.get('path', '/')
            secure = 'TRUE' if cookie.get('secure', False) else 'FALSE'
            expiration = int(cookie.get('expirationDate', 0))
            name = cookie.get('name', '')
            value = cookie.get('value', '')

            # Netscape format: domain, host_only, path, secure, expiration, name, value
            f.write(f"{domain}\t{host_only}\t{path}\t{secure}\t{expiration}\t{name}\t{value}\n")

    print(f"Converted {len(cookies)} cookies from JSON to Netscape format")
    print(f"Saved to: {output_file}")

if __name__ == '__main__':
    json_to_netscape('instagram_cookies.json', 'instagram_cookies.txt')
